var SampleFlowsheetData = function(){
	var flowsheet = {
			entries : [
			                {name:"Systolic blood pressure",value:"95 mmHg",dataType:"numeric",classType:"Test", obs_date: "2001-01-12"},
			                {name:"diastolic blood pressure",value:"55 mmHg",dataType:"numeric",classType:"Diagnosis", obs_date: "2002-01-12"},
			                {name:"Temparature (C)",value:"103 DEG C",dataType:"numeric",classType:"Finding", obs_date: "2003-01-12"},
			                {name:"Pregnancy status",value:"false",dataType:"boolean",classType:"Finding", obs_date: "2004-01-12"},
			                {name:"Problem added",value:"Dermatitis",dataType:"non-numeric",classType:"Finding", obs_date: "2010-01-12"},
			                {name:"Systolic blood pressure",value:"95 mmHg",dataType:"numeric",classType:"Test", obs_date: "2001-01-12"},
			                {name:"diastolic blood pressure",value:"55 mmHg",dataType:"numeric",classType:"Diagnosis", obs_date: "2002-01-12"},
			                {name:"Temparature (C)",value:"103 DEG C",dataType:"numeric",classType:"Finding", obs_date: "2003-01-12"},
			                {name:"Pregnancy status",value:"false",dataType:"boolean",classType:"Finding", obs_date: "2004-01-12"},
			                {name:"Problem added",value:"Dermatitis",dataType:"non-numeric",classType:"Finding", obs_date: "2010-01-12"},
			                {name:"Systolic blood pressure",value:"95 mmHg",dataType:"numeric",classType:"Test", obs_date: "2001-01-12"},
			                {name:"diastolic blood pressure",value:"55 mmHg",dataType:"numeric",classType:"Diagnosis", obs_date: "2002-01-12"},
			                {name:"Temparature (C)",value:"103 DEG C",dataType:"numeric",classType:"Finding", obs_date: "2003-01-12"},
			                {name:"Pregnancy status",value:"false",dataType:"boolean",classType:"Finding", obs_date: "2004-01-12"},
			                {name:"Problem added",value:"Dermatitis",dataType:"non-numeric",classType:"Finding", obs_date: "2010-01-12"},
			                {name:"Systolic blood pressure",value:"95 mmHg",dataType:"numeric",classType:"Test", obs_date: "2001-01-12"},
			                {name:"diastolic blood pressure",value:"55 mmHg",dataType:"numeric",classType:"Diagnosis", obs_date: "2002-01-12"},
			                {name:"Temparature (C)",value:"103 DEG C",dataType:"numeric",classType:"Finding", obs_date: "2003-01-12"},
			                {name:"Pregnancy status",value:"false",dataType:"boolean",classType:"Finding", obs_date: "2004-01-12"},
			                {name:"Problem added",value:"Dermatitis",dataType:"non-numeric",classType:"Finding", obs_date: "2010-01-12"},
			                {name:"Systolic blood pressure",value:"95 mmHg",dataType:"numeric",classType:"Test", obs_date: "2001-01-12"},
			                {name:"diastolic blood pressure",value:"55 mmHg",dataType:"numeric",classType:"Diagnosis", obs_date: "2002-01-12"},
			                {name:"Temparature (C)",value:"103 DEG C",dataType:"numeric",classType:"Finding", obs_date: "2003-01-12"},
			                {name:"Pregnancy status",value:"false",dataType:"boolean",classType:"Finding", obs_date: "2004-01-12"},
			                {name:"Problem added",value:"Dermatitis",dataType:"non-numeric",classType:"Finding", obs_date: "2010-01-12"},
			                {name:"Systolic blood pressure",value:"95 mmHg",dataType:"numeric",classType:"Test", obs_date: "2001-01-12"},
			                {name:"diastolic blood pressure",value:"55 mmHg",dataType:"numeric",classType:"Diagnosis", obs_date: "2002-01-12"},
			                {name:"Temparature (C)",value:"103 DEG C",dataType:"numeric",classType:"Finding", obs_date: "2003-01-12"},
			                {name:"Pregnancy status",value:"false",dataType:"boolean",classType:"Finding", obs_date: "2004-01-12"},
			                {name:"Problem added",value:"Dermatitis",dataType:"non-numeric",classType:"Finding", obs_date: "2010-01-12"},
			                {name:"Systolic blood pressure",value:"95 mmHg",dataType:"numeric",classType:"Test", obs_date: "2001-01-12"},
			                {name:"diastolic blood pressure",value:"55 mmHg",dataType:"numeric",classType:"Diagnosis", obs_date: "2002-01-12"},
			                {name:"Temparature (C)",value:"103 DEG C",dataType:"numeric",classType:"Finding", obs_date: "2003-01-12"},
			                {name:"Pregnancy status",value:"false",dataType:"boolean",classType:"Finding", obs_date: "2004-01-12"},
			                {name:"Problem added",value:"Dermatitis",dataType:"non-numeric",classType:"Finding", obs_date: "2010-01-12"},
			                {name:"Systolic blood pressure",value:"95 mmHg",dataType:"numeric",classType:"Test", obs_date: "2001-01-12"},
			                {name:"diastolic blood pressure",value:"55 mmHg",dataType:"numeric",classType:"Diagnosis", obs_date: "2002-01-12"},
			                {name:"Temparature (C)",value:"103 DEG C",dataType:"numeric",classType:"Finding", obs_date: "2003-01-12"},
			                {name:"Pregnancy status",value:"false",dataType:"boolean",classType:"Finding", obs_date: "2004-01-12"},
			                {name:"Problem added",value:"Dermatitis",dataType:"non-numeric",classType:"Finding", obs_date: "2010-01-12"},
			                {name:"Systolic blood pressure",value:"95 mmHg",dataType:"numeric",classType:"Test", obs_date: "2001-01-12"},
			                {name:"diastolic blood pressure",value:"55 mmHg",dataType:"numeric",classType:"Diagnosis", obs_date: "2002-01-12"},
			                {name:"Temparature (C)",value:"103 DEG C",dataType:"numeric",classType:"Finding", obs_date: "2003-01-12"},
			                {name:"Pregnancy status",value:"false",dataType:"boolean",classType:"Finding", obs_date: "2004-01-12"},
			                {name:"Problem added",value:"Dermatitis",dataType:"non-numeric",classType:"Finding", obs_date: "2010-01-12"},
			                {name:"Systolic blood pressure",value:"95 mmHg",dataType:"numeric",classType:"Test", obs_date: "2001-01-12"},
			                {name:"diastolic blood pressure",value:"55 mmHg",dataType:"numeric",classType:"Diagnosis", obs_date: "2002-01-12"},
			                {name:"Temparature (C)",value:"103 DEG C",dataType:"numeric",classType:"Finding", obs_date: "2003-01-12"},
			                {name:"Pregnancy status",value:"false",dataType:"boolean",classType:"Finding", obs_date: "2004-01-12"},
			                {name:"Problem added",value:"Dermatitis",dataType:"non-numeric",classType:"Finding", obs_date: "2010-01-12"},
			                {name:"Systolic blood pressure",value:"95 mmHg",dataType:"numeric",classType:"Test", obs_date: "2001-01-12"},
			                {name:"diastolic blood pressure",value:"55 mmHg",dataType:"numeric",classType:"Diagnosis", obs_date: "2002-01-12"},
			                {name:"Temparature (C)",value:"103 DEG C",dataType:"numeric",classType:"Finding", obs_date: "2003-01-12"},
			                {name:"Pregnancy status",value:"false",dataType:"boolean",classType:"Finding", obs_date: "2004-01-12"},
			                {name:"Problem added",value:"Dermatitis",dataType:"non-numeric",classType:"Finding", obs_date: "2010-01-12"},
			                {name:"Systolic blood pressure",value:"95 mmHg",dataType:"numeric",classType:"Test", obs_date: "2001-01-12"},
			                {name:"diastolic blood pressure",value:"55 mmHg",dataType:"numeric",classType:"Diagnosis", obs_date: "2002-01-12"},
			                {name:"Temparature (C)",value:"103 DEG C",dataType:"numeric",classType:"Finding", obs_date: "2003-01-12"},
			                {name:"Pregnancy status",value:"false",dataType:"boolean",classType:"Finding", obs_date: "2004-01-12"},
			                {name:"Problem added",value:"Dermatitis",dataType:"non-numeric",classType:"Finding", obs_date: "2010-01-12"},
			                {name:"Systolic blood pressure",value:"95 mmHg",dataType:"numeric",classType:"Test", obs_date: "2001-01-12"},
			                {name:"diastolic blood pressure",value:"55 mmHg",dataType:"numeric",classType:"Diagnosis", obs_date: "2002-01-12"},
			                {name:"Temparature (C)",value:"103 DEG C",dataType:"numeric",classType:"Finding", obs_date: "2003-01-12"},
			                {name:"Pregnancy status",value:"false",dataType:"boolean",classType:"Finding", obs_date: "2004-01-12"},
			                {name:"Problem added",value:"Dermatitis",dataType:"non-numeric",classType:"Finding", obs_date: "2010-01-12"}
			                ]
	};
	return flowsheet ;
}